### ISSUE TITLE
How to use it with Windows 10 ?

### ISSUE THREAD

**Issue by jumperrg** [impsnldavid/imp.push#7] opened 2023-03-24 16:35 UTC
Hi! 
I tried to use it, but didn't find any documentation, or tutorials, how to get it work with WIndows. Could you give a hint how to build it properly, and how the end app should look like ? 

Thanks!

**Comment by pixsperdavid** [comment] 2023-03-24 16:54
Duplicate of #6

**Closed as completed by pixsperdavid** 2023-03-24 16:54 UTC
